In [7]:
import pandas as pd
import numpy as np

In [38]:
columns=['documentId', "sentenceId","content"]
document = pd.read_csv('sample.csv', delimiter=',', header=0, names=columns)
sentence_ids = document["sentenceId"].values
sentence_ids

array([1, 2])

In [21]:
document_ids = [1,1,1,1,2,2,2,2]
sentence_ids = [1,2,3,4,1,2,3,4]
for doc_id, sentence_id in zip(document_ids, sentence_ids):
    print(doc_id, sentence_id)

1 1
1 2
1 3
1 4
2 1
2 2
2 3
2 4


In [32]:
np.column_stack((document_ids, sentence_ids))

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]])

In [19]:
sections

array([1, 2])

In [12]:
ids = np.array([[1,1], [1,2], [1,3], [1,4], [2,1], [2,2], [2,3], [2,4]])
sections = np.unique(ids[:,0])
current_section = ids[0,0]